---
version: "3"

services:
  database:
    image: mariadb:10.4.5-bionic
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  keystone:
    image: tripleomaster/centos-binary-keystone:current-tripleo
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
      KEYSTONE_ADMIN_PASSWORD: ${KEYSTONE_ADMIN_PASSWORD}
      KEYSTONE_DB_HOST: database
      KEYSTONE_DB_USER: keystone
      KEYSTONE_DB_NAME: keystone
      KEYSTONE_DB_PASSWORD: ${KEYSTONE_DB_PASSWORD}
    volumes:
      - "./keystone/kolla-config.json:/var/lib/kolla/config_files/config.json:ro"
      - "./keystone/src:/var/lib/kolla/config_files/src:ro"
      - "./keystone/keystone-init.py:/docker/keystone-init.py"
    ports:
      - "127.0.0.1:5000:5000"

volumes:
  mysql:
